# Generated by Django 4.1.3 on 2022-11-19 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EstoqueMateria",
            fields=[
                ("id_materia", models.IntegerField(primary_key=True, serialize=False)),
                ("id_lote", models.IntegerField()),
                ("dat_saida", models.DateTimeField(blank=True, null=True)),
                ("qtd_estoque", models.FloatField(blank=True, null=True)),
                ("item", models.CharField(blank=True, max_length=45, null=True)),
                ("ord_compra", models.IntegerField(blank=True, null=True)),
                ("dat_entrada", models.DateTimeField(blank=True, null=True)),
                ("dat_validade", models.DateTimeField(blank=True, null=True)),
                ("qtd_saida", models.FloatField(blank=True, null=True)),
            ],
            options={"db_table": "estoque_materia", "managed": False,},
        ),
        migrations.CreateModel(
            name="EstoqueMinimo",
            fields=[
                (
                    "id_estoque_minimo",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("qtd_min", models.FloatField(blank=True, null=True)),
            ],
            options={"db_table": "estoque_minimo", "managed": False,},
        ),
        migrations.CreateModel(
            name="EstoqueMinimoMateria",
            fields=[
                (
                    "id_estoque_minimo",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("qtd_min", models.FloatField(blank=True, null=True)),
                ("descricao", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={"db_table": "estoque_minimo_materia", "managed": False,},
        ),
        migrations.CreateModel(
            name="EstoqueProduto",
            fields=[
                (
                    "id_estoque_produto",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("estoque_produto", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "estoque_produto", "managed": False,},
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id_fornecedor",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("materia", models.CharField(blank=True, max_length=45, null=True)),
                ("quantidade", models.FloatField(blank=True, null=True)),
                ("valor", models.FloatField(blank=True, null=True)),
                ("descricao", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fornecedorcol",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
            ],
            options={"db_table": "fornecedor", "managed": False,},
        ),
        migrations.CreateModel(
            name="Manutencao",
            fields=[
                (
                    "id_manutencao",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("dat_manutencao", models.DateTimeField(blank=True, null=True)),
                ("dat_revisao", models.DateTimeField(blank=True, null=True)),
                (
                    "iten_substituido",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
            ],
            options={"db_table": "manutencao", "managed": False,},
        ),
        migrations.CreateModel(
            name="Maquina",
            fields=[
                ("id_maq", models.IntegerField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(blank=True, max_length=100, null=True)),
                ("turno", models.CharField(blank=True, max_length=45, null=True)),
                ("tip_maq", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "itns_substituido",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                (
                    "maq_producao",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
            ],
            options={"db_table": "maquina", "managed": False,},
        ),
        migrations.CreateModel(
            name="Operador",
            fields=[
                ("id_operador", models.IntegerField(primary_key=True, serialize=False)),
                ("producao", models.CharField(blank=True, max_length=45, null=True)),
                ("dat_ingre_funcao", models.DateTimeField(blank=True, null=True)),
                ("turno", models.CharField(blank=True, max_length=45, null=True)),
                ("funcao", models.CharField(blank=True, max_length=45, null=True)),
                ("setor", models.CharField(blank=True, max_length=45, null=True)),
                ("dat_uso_maq", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={"db_table": "operador", "managed": False,},
        ),
        migrations.CreateModel(
            name="Peca",
            fields=[
                ("id_peca", models.IntegerField(primary_key=True, serialize=False)),
                ("qtd_iten", models.FloatField(blank=True, null=True)),
                ("descricao", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={"db_table": "peca", "managed": False,},
        ),
        migrations.CreateModel(
            name="Producao",
            fields=[
                ("id_producao", models.IntegerField(primary_key=True, serialize=False)),
                ("dat_fabricacao", models.DateField(blank=True, null=True)),
                ("qtd_prodcao_item", models.FloatField(blank=True, null=True)),
                ("lote_producao", models.IntegerField(blank=True, null=True)),
                ("linha_producao", models.IntegerField(blank=True, null=True)),
                ("qtd_descarte", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "producao", "managed": False,},
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                ("id_prod", models.IntegerField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={"db_table": "produto", "managed": False,},
        ),
        migrations.CreateModel(
            name="SpatialRefSys",
            fields=[
                ("srid", models.IntegerField(primary_key=True, serialize=False)),
                ("auth_name", models.CharField(blank=True, max_length=256, null=True)),
                ("auth_srid", models.IntegerField(blank=True, null=True)),
                ("srtext", models.CharField(blank=True, max_length=2048, null=True)),
                ("proj4text", models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={"db_table": "spatial_ref_sys", "managed": False,},
        ),
        migrations.CreateModel(
            name="Tecnico",
            fields=[
                ("id_tecnico", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "especialidade",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
            ],
            options={"db_table": "tecnico", "managed": False,},
        ),
        migrations.CreateModel(
            name="Verificacao",
            fields=[
                (
                    "id_verificacao",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={"db_table": "verificacao", "managed": False,},
        ),
        migrations.CreateModel(
            name="FornecedorHasEstoqueMateria",
            fields=[
                (
                    "fornecedor_id_fornecedor",
                    models.OneToOneField(
                        db_column="fornecedor_id_fornecedor",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="main.fornecedor",
                    ),
                ),
            ],
            options={"db_table": "fornecedor_has_estoque_materia", "managed": False,},
        ),
    ]
